spring:
  # 设置数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/boot?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

  # 页面配置
  thymeleaf:
    cache: false

  mvc:
    view:
      suffix: .html
      prefix: /templates/

logging:
  level: debug

server:
  # 设置端口以及访问前缀
  port: 8080